name: 'Download GitHub Release'
description: 'Download any files from Github Releases'
author: 'Leon Kiefer'
inputs: 
  repository:
    description: |
      The repository from where to download the files.
      Given as <user>/<repository>
    required: true
  tag:
    description: 'The version tag of the release'
    required: true
  file:
    description: |
      The file which should be downloaded.
      If not specified download the source code. 
    required: false
  path:
    description: 'download directory'
    default: './'
  token:
    description: 'Github token to access private repositories'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'download'
  color: 'blue'
